apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-nodeport-service
  namespace: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 8000
      targetPort: 8000
