"""hola


Revision ID: 0124d644a4a2
Revises: cada03d64d21
Create Date: 2024-04-17 12:44:24.744079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from db import Page, Element, Attribute, Change, create_db_and_tables

# revision identifiers, used by Alembic.
revision: str = "0124d644a4a2"
down_revision: Union[str, None] = "cada03d64d21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    create_db_and_tables()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sqlmodel.SQLModel.metadata.drop_all(op.get_bind())
    # ### end Alembic commands ###
