"""fk_element

Revision ID: b2297a65dd9b
Revises: e34b4761500c
Create Date: 2024-04-19 10:05:27.495419

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2297a65dd9b"
down_revision: Union[str, None] = "e34b4761500c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("change", schema=None) as batch_op:
        batch_op.add_column(sa.Column("elem_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("FK_added", "element", ["elem_id"], ["id_element"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("change", schema=None) as batch_op:
        batch_op.drop_constraint("FK_added", type_="foreignkey")
        batch_op.drop_column("elem_id")

    # ### end Alembic commands ###
